name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: "poetry"

    - name: Install dependencies
      run: |
        poetry install

    - name: Run ruff
      run: |
        poetry run ruff check .

    - name: Run tests with pytest
      run: |
        poetry run pytest .
